"""
Django settings for cooking project.

Generated by 'django-admin startproject' using Django 3.2.4.

"""
import os
from datetime import timedelta
from pathlib import Path
import json
from posixpath import join

from . import conf



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# old dj vers BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# /mnt/c/Users/tanja/Desktop/cook/backend/cooking
# /mnt/c/Users/tanja/Desktop/cook/backend/cooking/conf/config.json
# config_path = [os.path.join(BASE_DIR,"conf","config.json")]

with open('/mnt/c/Users/tanja/Desktop/secrets/idea_proj/conf/config.json') as fh:
    config = json.load(fh)

# with open('/etc/config.json') as fh:
#     config = json.load(fh)
    

SECRET_KEY = config.get('SECRET_KEY')


DEBUG = True

ALLOWED_HOSTS = ['*']
#CORS_ORIGIN_WHITELIST = ('http://127.0.0.1:8080','http://localhost:8080','http://localhost:8000')
AUTH_USER_MODEL = "users.User"

INSTALLED_APPS = [
    #'corsheaders',
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
]

#third-
INSTALLED_APPS += [
    # should be on the top (see above)'corsheaders',
    'django_filters',
    'djoser',
    'mptt',    
    'storages',
    'taggit',
    'taggit_serializer',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
   
    
]
# custom
INSTALLED_APPS += [
    'ideas.apps.IdeasConfig',
    'profiles.apps.ProfilesConfig',
    'comments.apps.CommentsConfig',
    'timestamp',
    'users',
    

]

MIDDLEWARE = [    
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]
INTERNAL_IPS = ['127.0.0.1']

ROOT_URLCONF = 'cooking.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.joinpath('templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'cooking.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        # 'ENGINE': 'django.db.backends.postgresql',
        'NAME': config.get('DB_NAME'),
        'USER':config.get('DB_USER'),
        'PASSWORD':config.get('DB_PSW'),
        'HOST':'localhost',
        'PORT':'5432',

    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
######## AWS ###################################
AWS_ACCESS_KEY_ID = config.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False # key not in url 
AWS_S3_MAX_MEMORY_SIZE = 2200000
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

AWS_S3_REGION_NAME = "eu-central-1"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# send grid
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = config.get('MY_EMAIL')
EMAIL_HOST_PASSWORD = config.get('EMAIL_HOST_PASSWORD')

# from social_core.backends import google

# class GoogleOAuth2(google.GoogleOAuth2):
#     STATE_PARAMETER = False
#     print("Done")

AUTHENTICATION_BACKENDS = (       
    'social_core.backends.google.GoogleOAuth2',        
    'django.contrib.auth.backends.ModelBackend',
)
# SOCIAL_AUTH_POSTGRES_JSONFIELD = True

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY= config.get('GOOGLE_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET =config.get('GOOGLE_SECRET')

# temp for djoser activation + need migrate for table
# SITE_ID =1

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# drf
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticatedOrReadOnly',),
    'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework_simplejwt.authentication.JWTAuthentication',),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    # 'DEFAULT_RENDERER_CLASSES': (
    #     'rest_framework.renderers.JSONRenderer', 'rest_framework.renderers.BrowsableAPIRenderer',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 6 # see also front helpers.limit = 6    

}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=35),
    # 'REFRESH_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=12),
    'AUTH_HEADER_TYPES': ('JWT','Bearer'),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    # 'location.to.custom.token.CustomJWTToken' 

}


DJOSER = {
    'ACTIVATION_URL': 'activate/{uid}/{token}',
    'LOGIN_FIELD': 'email',
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': True,
    'PASSWORD_RESET_CONFIRM_URL': 'password/reset/confirm/{uid}/{token}',    
    'SEND_CONFIRMATION_EMAIL': True,
    'SEND_ACTIVATION_EMAIL': True,
    'SET_USERNAME_RETYPE': True,  # option
    'SET_PASSWORD_RETYPE': True,
    'PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND':True,# if user email doesn't exist in db||=> 400 BAD REQ resp  
    
    # 'CREATE_SESSION_ON_LOGIN': learn point
    'SERIALIZERS': {
        'user_create': 'djoser.serializers.UserCreateSerializer',
        'user': 'api.serializers.account.user_serializer.UserSerializer',
        'current_user': 'api.serializers.account.user_serializer.UserSerializer',
        'user_delete': 'djoser.serializers.UserDeleteSerializer',    
    },
    'USER_CREATE_PASSWORD_RETYPE': True,
    'USERNAME_CHANGED_EMAIL_CONFIRMATION': True,
    'USERNAME_RESET_CONFIRM_URL': 'email/reset/confirm/{uid}/{token}',
    
}
# problem with auth via social: State could not be found in server-side session data
# Think SESSION_COOKIE_SECURE = False
# SESSION_COOKIE_SAMESITE = None


STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR.joinpath('static')]
# STATIC_ROOT = os.path.join(BASE_DIR,"static")

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



LOGGING = conf.LOGGING
